services:
  postgres:
    image: postgres:17
    container_name: postgres_db_openlabs
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: redis_queue_openlabs
    command: ["redis-server", "--loglevel", "warning", "--requirepass", "${REDIS_QUEUE_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - fastapi_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_QUEUE_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    build:
      target: worker
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - fastapi_network

  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: fastapi_app_openlabs
    env_file:
      - .env
    ports:
      - "${API_BIND_ADDR}:${API_PORT}:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - fastapi_network

  init:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: fastapi_init_openlabs
    env_file:
      - .env
    command: ["python", "-m", "src.scripts.create_admin"]
    depends_on:
      fastapi:
        condition: service_healthy
    networks:
      - fastapi_network
    restart: on-failure

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${API_URL}
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      NODE_ENV: production
    depends_on:
      fastapi:
        condition: service_healthy
    networks:
      - fastapi_network
    profiles:
      - frontend

volumes:
  postgres_data:
  redis_data:

networks:
  fastapi_network:
    driver: bridge