services:
  fastapi:
    build:
      target: api_debug
    container_name: fastapi_app_dev
    volumes:
      - .:/code
    ports:
      - "5678:5678"
    command: [
      "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client",
      "-m", "uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload", "--workers", "4"
    ]