version: '3.8'

x-common-variables: &common-variables
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-openlabs}
  POSTGRES_SERVER: postgres
  POSTGRES_PORT: 5432
  REDIS_QUEUE_HOST: redis
  REDIS_QUEUE_PORT: 6379
  REDIS_QUEUE_PASSWORD: ${REDIS_QUEUE_PASSWORD:-ChangeMe123!}

services:
  postgres:
    image: postgres:16
    environment:
      <<: *common-variables
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_QUEUE_PASSWORD:-ChangeMe123!}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      target: prod
    environment:
      <<: *common-variables
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${API_PORT:-8000}:80"
    volumes:
      - ./api/.env:/code/.env:ro
      - ./.git:/code/.git:ro

  worker:
    build:
      context: ./api
      target: worker
    environment:
      <<: *common-variables
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./api/.env:/code/.env:ro
      - ./.git:/code/.git:ro

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-http://localhost:8000}
    depends_on:
      - api
    profiles:
      - frontend

volumes:
  postgres_data: