version: '3.8'

x-common-variables: &common-variables
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-openlabs_test}
  POSTGRES_SERVER: postgres
  POSTGRES_PORT: 5432
  REDIS_QUEUE_HOST: redis
  REDIS_QUEUE_PORT: 6379
  REDIS_QUEUE_PASSWORD: ${REDIS_QUEUE_PASSWORD:-ChangeMe123!}
  CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000,http://localhost:3001}
  CORS_CREDENTIALS: ${CORS_CREDENTIALS:-true}
  CORS_METHODS: ${CORS_METHODS:-*}
  CORS_HEADERS: ${CORS_HEADERS:-*}

services:
  postgres:
    image: postgres:16
    environment:
      <<: *common-variables
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_QUEUE_PASSWORD:-ChangeMe123!}
    tmpfs:
      - /data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-test:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: api_test
    environment:
      <<: *common-variables
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./.env:/code/.env:ro
      - ./.git:/code/.git:ro
      - ./api/.testing-out:/code/.testing-out
    command: ["python", "-m", "pytest", "-v", "--tb=short"]