services:
  fastapi:
    build:
      target: dev
    command: >
      uvicorn tests.integration.main_test:app --host 0.0.0.0 --port 80
    volumes:
      - ./.coverage-out:/code/.coverage-out
    environment:
      - COVERAGE_PROCESS_START=/code/pyproject.toml
      - COVERAGE_FILE=/code/.coverage-out/.coverage