name: API - AWS Tests

on:
  workflow_run:
    workflows: ["API - Integration Tests"]
    types:
      - completed
    branches:
      - '**'

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINERS_RYUK_DISABLED: "true"
      
    steps:
      # Install docker
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.workflow_run.head_sha }}

      # Create .env file with defaults
      - name: Set default ENV values
        run: |
          cp .env.example .env

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      # Install dependencies
      - name: Install dependencies
        run: |
          cd api
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      # Run Tests
      - name: Run AWS Tests
        env:
          INTEGRATION_TEST_AWS_ACCESS_KEY: ${{ secrets.INTEGRATION_TEST_AWS_ACCESS_KEY }}
          INTEGRATION_TEST_AWS_SECRET_KEY: ${{ secrets.INTEGRATION_TEST_AWS_SECRET_KEY }}
        run: |
          cd api
          pytest -m aws --no-cov 
