name: Reusable Provider Test

on:
  workflow_call:
    inputs:
      provider:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: false
      AWS_SECRET_KEY:
        required: false

jobs:
  run-provider-test:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINERS_RYUK_DISABLED: "true"
      # AWS
      INTEGRATION_TEST_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      INTEGRATION_TEST_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            api/requirements.txt
            api/dev-requirements.txt

      - name: Install dependencies
        run: |
          cd api
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Run ${{ inputs.provider }} Tests
        run: |
          cd api
          pytest -m ${{ inputs.provider }} --no-cov

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: api-${{ inputs.provider }}-test-logs
          path: api/testing-out/