name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Create .env file with defaults
      - name: Set default ENV values
        run: |
          cp .env.example .env

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      # Run Tests
      - name: Run Unit Tests
        run: |
          pytest -m unit